spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employees?serverTimezone=GMT%2B8
#${MYSQL-USER:没有含义}
#    username: ${MYSQL-USER:root}
#    password: ${MYSQL-PWD:123}
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
server:
  port: 8070
mapper:
  not-empty: false
  identity: MYSQL
