spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pig?serverTimezone=GMT%2B8
    username: ${MYSQL-USER:root}
    password: ${MYSQL-PWD:123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    suffix: .ftl                                 # 设置模板后缀名
    content-type: text/html                      # 设置文档类型
    charset: UTF-8                               # 设置页面编码格式
    cache: false                                 # 设置页面缓存
    template-loader-path: classpath:/templates   # 设置ftl文件路径
    mvc:
      static-path-pattern: /static         # 设置静态文件路径，js,css等
  application:
    name: sakura-user
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8090
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.model


